server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://<loki-url>:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'express-logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: express-app
          __path__: ../app.log
